revChatGPT/Exceptions.py,sha256=70Dmggf9AQGBKnfg0NJJmyKugBUig42THIs6OD5jeMA,632
revChatGPT/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
revChatGPT/__main__.py,sha256=4yuG7KF4FEELhMbExgKTesJRj8IxV9YiPIusH-YCpA0,5905
revChatGPT/revChatGPT.py,sha256=CABMi7_n1drpCmKxPUdBq0oOcCb9ZaqM7pseuaFEX_I,21120
revChatGPT-0.0a41.dist-info/LICENSE,sha256=gXf5dRMhNSbfLPYYTY_5hsZ1r7UU1OaKQEAQUhuIBkM,18092
revChatGPT-0.0a41.dist-info/METADATA,sha256=RqEW9SLiy6LbJfwcK-FdLBYZ2ZwJJpK1fyHTJb7nDrg,2731
revChatGPT-0.0a41.dist-info/WHEEL,sha256=2wepM1nk4DS4eFpYrW1TTqPcoGNfHhhO_i5m4cOimbo,92
revChatGPT-0.0a41.dist-info/entry_points.txt,sha256=XWRsRhbycEK0s0FlJsWUcWPSuZ5Gr0InFuJdEiKeUiE,56
revChatGPT-0.0a41.dist-info/top_level.txt,sha256=6O3ay3adff-Qrq0tGYaEe_XXhvCZ5vGC9AshCmZzRMA,11
revChatGPT-0.0a41.dist-info/RECORD,,
