revChatGPT/Exceptions.py,sha256=70Dmggf9AQGBKnfg0NJJmyKugBUig42THIs6OD5jeMA,632
revChatGPT/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
revChatGPT/__main__.py,sha256=qTA6JOxPkqu4hSjtT5XSlqRBraITfzmIb-b1qHgcWrs,5760
revChatGPT/revChatGPT.py,sha256=5klidquM1etXKSWTIXrXjO6fi1faZHsHLXf1w3ghWQc,18969
revChatGPT-0.0.37.1.dist-info/LICENSE,sha256=gXf5dRMhNSbfLPYYTY_5hsZ1r7UU1OaKQEAQUhuIBkM,18092
revChatGPT-0.0.37.1.dist-info/METADATA,sha256=5I0iIACBVMKWU13bA2pLlu_UqapOTeY1zXkrolyYbtU,2397
revChatGPT-0.0.37.1.dist-info/WHEEL,sha256=2wepM1nk4DS4eFpYrW1TTqPcoGNfHhhO_i5m4cOimbo,92
revChatGPT-0.0.37.1.dist-info/entry_points.txt,sha256=XWRsRhbycEK0s0FlJsWUcWPSuZ5Gr0InFuJdEiKeUiE,56
revChatGPT-0.0.37.1.dist-info/top_level.txt,sha256=6O3ay3adff-Qrq0tGYaEe_XXhvCZ5vGC9AshCmZzRMA,11
revChatGPT-0.0.37.1.dist-info/RECORD,,
