revChatGPT/Exceptions.py,sha256=70Dmggf9AQGBKnfg0NJJmyKugBUig42THIs6OD5jeMA,632
revChatGPT/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
revChatGPT/__main__.py,sha256=RT69V1wO9Qo2ZYrEUMvsRw3QdxWZ0gkLBdc7dHHzBKU,6076
revChatGPT/revChatGPT.py,sha256=KWF8IDGubpciFIyprO-tjboAQmRnj7T8PBeFBvmEZ6s,21404
revChatGPT-0.0.38.8.dist-info/LICENSE,sha256=gXf5dRMhNSbfLPYYTY_5hsZ1r7UU1OaKQEAQUhuIBkM,18092
revChatGPT-0.0.38.8.dist-info/METADATA,sha256=6Sh9VGwKnTRzgJZJC4M2cpJFuI11vNx_mNk-jECB7co,2743
revChatGPT-0.0.38.8.dist-info/WHEEL,sha256=2wepM1nk4DS4eFpYrW1TTqPcoGNfHhhO_i5m4cOimbo,92
revChatGPT-0.0.38.8.dist-info/entry_points.txt,sha256=XWRsRhbycEK0s0FlJsWUcWPSuZ5Gr0InFuJdEiKeUiE,56
revChatGPT-0.0.38.8.dist-info/top_level.txt,sha256=6O3ay3adff-Qrq0tGYaEe_XXhvCZ5vGC9AshCmZzRMA,11
revChatGPT-0.0.38.8.dist-info/RECORD,,
